// Generate sw.js with a build-stamped cache name and a precache list read from
// the actual dist output, so a rebuild always invalidates the old cache.
import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { join, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DIST = join(ROOT, 'dist');

function walk(dir, acc = []) {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) walk(p, acc);
    else acc.push(p);
  }
  return acc;
}

const files = walk(DIST).map((p) => './' + relative(DIST, p).split('\\').join('/'));

// App shell: everything except the per-problem statements, which are large,
// numerous, and only needed once a problem is opened.
const shell = files.filter((f) => !f.startsWith('./statements/') && f !== './sw.js');
const statementCount = files.length - shell.length;

// Cache name derives from shell content, so any code/content change busts it.
const h = createHash('sha256');
for (const f of shell.sort()) h.update(f).update(readFileSync(join(DIST, f.slice(2))));
const VERSION = h.digest('hex').slice(0, 12);

const sw = `// Generated by scripts/make-sw.mjs — do not edit by hand.
const VERSION = '${VERSION}';
const SHELL_CACHE = 'acm-shell-' + VERSION;
const DATA_CACHE = 'acm-data-v1';

const SHELL = ${JSON.stringify(shell, null, 2)};

// Resolve against the SW's own location so cache keys are absolute URLs that
// match what the browser actually requests. Storing the './...' forms would
// key them relative to the SW script and every lookup would miss.
const url = (p) => new URL(p, self.location).href;

self.addEventListener('install', (e) => {
  e.waitUntil(
    caches.open(SHELL_CACHE)
      // addAll is atomic: one 404 aborts the whole install, which is what we
      // want — a half-precached shell is worse than no offline support.
      .then((c) => c.addAll(SHELL.map(url)))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(
        keys.filter((k) => k.startsWith('acm-shell-') && k !== SHELL_CACHE)
            .map((k) => caches.delete(k))
      ))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;  // let LeetCode images go to network

  // Navigations: serve the shell so deep links and offline launches both work.
  if (req.mode === 'navigate') {
    e.respondWith(
      caches.match(url('./index.html')).then((r) => r || fetch(req))
    );
    return;
  }

  // Statements: cache-first, then populate on demand.
  if (url.pathname.includes('/statements/')) {
    e.respondWith(
      caches.match(req).then((hit) => {
        if (hit) return hit;
        return fetch(req).then((res) => {
          if (res.ok) {
            const copy = res.clone();
            caches.open(DATA_CACHE).then((c) => c.put(req, copy));
          }
          return res;
        });
      })
    );
    return;
  }

  // Everything else: cache-first with network fallback.
  e.respondWith(caches.match(req).then((hit) => hit || fetch(req)));
});
`;

writeFileSync(join(DIST, 'sw.js'), sw);
console.log(`✓ sw.js written`);
console.log(`  version: ${VERSION}`);
console.log(`  precached shell: ${shell.length} files`);
console.log(`  statements (lazy): ${statementCount} files`);
